image:
- Visual Studio 2017

deploy: off

clone_depth: 5

init:
  # Remove any ENV settings related to OpenSSL-Win
  - ps: |
      Remove-Item env:SSL_CERT_DIR  -ErrorAction SilentlyContinue
      Remove-Item env:SSL_CERT_FILE -ErrorAction SilentlyContinue
      Remove-Item env:OPENSSL_CONF  -ErrorAction SilentlyContinue
      Remove-Item env:OPENSSL_DIR   -ErrorAction SilentlyContinue
      ren C:\Windows\System32\libssl-1_1-x64.dll    libssl-1_1-x64.dll_
      ren C:\Windows\System32\libcrypto-1_1-x64.dll libcrypto-1_1-x64.dll_

install:
  # Update MSYS2 / MinGW and install OpenSSL
  - ps: |
      git clone -q --depth=5 --no-tags --branch=master https://github.com/oneclick/rubyinstaller2.git    ./rubyinstaller2
      git clone -q --depth=5 --no-tags --branch=master https://github.com/ConnorAtherton/rb-readline.git ./ruby_readline
      git clone -q --depth=5 --no-tags --branch=trunk  https://github.com/ruby/ruby.git                  ./ruby
      $env:path = "C:\Ruby25-x64\bin;$env:path"
      .\trunk_msys2.ps1

build_script:
  # builds, installs
  - ps: ./1_0_build_install_64.ps1

test_script:
  # tests, generates logs and artifacts
  - ps: ./2_0_test.ps1

on_finish:
  - ps: |
      ren C:\Windows\System32\libssl-1_1-x64.dll_    libssl-1_1-x64.dll
      ren C:\Windows\System32\libcrypto-1_1-x64.dll_ libcrypto-1_1-x64.dll
